### ISSUE TITLE
opaque URI handling compared with java.net.URI

### ISSUE THREAD

**Issue by atikinn** [lemonlabsuk/scala-uri#11]
Hi there,

I've been playing with your nice library for parsing URI string and noticed a behavior not consistent with java.net.URI for opaque URI which do not have paths (https://docs.oracle.com/javase/8/docs/api/java/net/URI.html).

```
scala> new java.net.URI("mailto:java-net@java.sun.com").getPath
res0: String = null

scala> parse("mailto:java-net@java.sun.com").path
res1: String = /mailto:java-net@java.sun.com
```

Is it intentional?

**Comment by theon** [comment]
Hi! 

Thanks for raising this. Fixing the lack of mailto support has been on the todo list for a while.

This is now fixed as of version `0.5.5`. It will parse the email address as the path which I believe is the correct way to handle mailto URIs as per RFC 3986:

> For example, the URI <mailto:fred@example.com> has a path of "fred@example.com"

See [https://www.ietf.org/rfc/rfc3986.txt](https://www.ietf.org/rfc/rfc3986.txt)

Update to scala-uri [README](https://github.com/lemonlabsuk/scala-uri#mailto):

```scala
val mailto = Uri.parse("mailto:someone@example.com?subject=Hello")
mailto.scheme // This is Some(mailto")
mailto.path // This is "someone@example.com"
mailto.query.param("subject") // This is Some("Hello")
```
