### ISSUE TITLE
[feature request] Scala.js 1.0.0 support

### ISSUE THREAD

**Issue by exoego** [lemonlabsuk/scala-uri#117]
**Description**
I would like to use scala-uri with Scala.js 1.0.0.

Scala.js 1.0.0 is not officially announcend, but was released to Maven Centeral and available now.
Scala.js requires artifacts published for each major version of Scala.js (0.6.x / 1.x).

[Currently `scala-uri` is published only for Scala.js 0.6](https://github.com/lemonlabsuk/scala-uri/blob/495d4b01b8301d2447d08d326ae2ae5724a13ff1/project/plugins.sbt#L5).

I think it requires time until all Scala.js users migrates to Scala.js 1.0.0, so it would be great if `scala-uri` cross-publishes for Scala.js 0.6/1.0.
(Even scalatest is not published for Scala.js 1.0.0 yet !).

**Comment by theon** [comment]
👍 I'll get on this as soon as all dependencies have published with Scala.js 1.0.0

https://github.com/lemonlabsuk/scala-uri/pull/113

**Comment by exoego** [comment]
Thanks for working this on #145 👍👍👍

I am sorry to rush you in this ... but it would be really great if this library is published for Scala.js 1.0.
Again, many thanks for your years of effort on this project !!

**Comment by theon** [comment]
Sorry for the delay and lack of update.

I am currently getting linking errors locally when I try to compile locally for Scala.js 1.0 so can't yet publish. I'll try to figure out what is going on. The odd thing is that it seems to be compiling fine on travis.

This compiles fine:
```
SCALAJS_VERSION=0.6.32 sbt clean coverageOff ++2.13.1 scalaUriJS/test
```

This:
```
SCALAJS_VERSION=1.0.1 sbt clean coverageOff ++2.13.1 scalaUriJS/test
```

Gives me:
```
[error] Referring to non-existent class io.lemonlabs.uri.typesafe.TraversableParams$Ops
[error]   called from io.lemonlabs.uri.typesafe.TraversableParams$AllOps
[error]   called from io.lemonlabs.uri.typesafe.TraversableParams$ops$.toAllTraversableParamsOps(java.lang.Object,io.lemonlabs.uri.typesafe.TraversableParams)io.lemonlabs.uri.typesafe.TraversableParams$AllOps
[error]   called from io.lemonlabs.uri.QueryString$.fromTraversable(java.lang.Object,io.lemonlabs.uri.typesafe.TraversableParams,io.lemonlabs.uri.config.UriConfig)io.lemonlabs.uri.QueryString
[error]   called from io.lemonlabs.uri.QueryString$.fromPairs(java.lang.Object,scala.collection.immutable.Seq,io.lemonlabs.uri.typesafe.QueryKeyValue,io.lemonlabs.uri.config.UriConfig)io.lemonlabs.uri.QueryString
[error]   called from private io.lemonlabs.uri.NapGithubIssueTests.$anonfun$new$8()org.scalatest.compatible.Assertion
[error]   called from constructor io.lemonlabs.uri.NapGithubIssueTests.<init>()void
[error]   called from static constructor io.lemonlabs.uri.NapGithubIssueTests.<clinit>()void
[error]   called from core module analyzer

<followed by more similar>
```

I'm not sure what the problem is, but `TraversableParams$Ops` is a class generated by simulacrum

**Comment by exoego** [comment]
Thanks for sharing details.

Hmm, that sounds odd.
I cloned the repo and run 

```
SCALAJS_VERSION=0.6.32 sbt clean coverageOff ++2.13.1 scalaUriJS/test
SCALAJS_VERSION=1.0.1 sbt clean coverageOff ++2.13.1 scalaUriJS/test
```

resuling in success, as you said so on Travis CI.
My development machine runs Ubuntu 18 and Java 11.0.7.

I had seen `Referring to non-existent class` error in Scala.js many times.
But, for most cases, it can be resolved if the class is implemented for Scala.js and the last compile cache is `clean`-ed .

How about clean up your `~/.ivy2/cache` and `~/.coursier` just in case your locally-cached dependencies are broken ?

**Comment by theon** [comment]
Something clearly wrong with my local environment... Still no joy after clearing caches, clean clone, upgrading jdk, sbt.

I have, however, realised it's just the linking of the tests that I have an error with, so if I skip running the tests, I can publish. I'll have to rely on travis running those tests until I get to the bottom of it 😄 

Version `2.2.1` should now be available for both Scala.js `0.6.x` and `1.x`.
