### ISSUE TITLE
Public suffix com.bd

### ISSUE THREAD

**Issue by newffy** [lemonlabsuk/scala-uri#179]
There is no public suffix `com.bd` In `PublicSuffixes` sets

**Comment by theon** [comment]
Thanks for raising @newffy 

The set has `*.bd`, however we are not handling the wildcard correctly. I'll fix this. This set comes from https://publicsuffix.org/list/ and I missed the following from the specification:

> The wildcard character * (asterisk) matches any valid sequence of characters in a hostname part

**Comment by newffy** [comment]
Actually useful public suffix is `com.bd` : there are domains in *.com.bd delegated to different companies/apps

**Comment by theon** [comment]
Yes exactly. `*.bd` in the public suffix set means we should be returning `com.bd` and others such as the ones listed here: https://en.wikipedia.org/wiki/.bd#Second-Level_domain

**Comment by theon** [comment]
This has been fixed in version `2.2.4` which should be in maven central shortly. Let me know how you get on!

**Comment by newffy** [comment]
It works. Thanks a lot for the library and for your amazingly fast help!
