### ISSUE TITLE
Large port numbers are not accepted

### ISSUE THREAD

**Issue by dmurvihill** [lemonlabsuk/scala-uri#191]
**Describe the bug**
The parser seems to fail port numbers after 10 digits even though RFC 3981 imposes no limit on the length of a port number string.

**To Reproduce**

Tested on Scala 2.11, scala-uri 1.4.10 (let me know if this has already been fixed in 2.0)

```scala
import io.lemonlabs.uri.Url

val url = "hNu.u+m+-+q+://_%Ad:h%b1+%69:%E7@m'%c4&~%c2-%15%75.)%15c;%5a%FC$)*:10653127493172/*Q$F/%6A)%2a%9d@:@%6C/)@/%59%Fe@%49::/!!;:+@$z%e6:j%0c.%81::!%06z/@':+:o~@c%0D@@%06=%c3@:/,%16%6c:~@:@@%c3+:@@%60%F4s~-/%55:%b5@%BD%9e_:@:z:%a3%53/*%b7$//l:l@=%33%E5%B1:@.f@;%5b/%EA%35:j@%Ca,::xu/e:/r):@u'@%e3/%68u$&$;@*--%d4%c2$)::~%A3:M/%5a@@.:%3B,:(:@:::%b0/,@%57!-)@')@/q@@;%78:/@~&:~%5c(*(:@%C1-%3b:?//:?@/v#??:@?://@/"

Url.parse(url)
```

```
[info]   UriParsingException was thrown during property evaluation.
[info]     Message: Invalid URL could not be parsed. Invalid input '3', expected _path_for_authority, _maybe_query_string, _fragment or 'EOI' (line 1, column 78):
[info]   hNu.u+m+-+q+://_%Ad:h%b1+%69:%E7@m'%c4&~%c2-%15%75.)%15c;%5a%FC$)*:10653127493172/*Q$F/%6A)%2a%9d@:@%6C/)@/%59%Fe@%49::/!!;:+@$z%e6:j%0c.%81::!%06z/@':+:o~@c%0D@@%06=%c3@:/,%16%6c:~@:@@%c3+:@@%60%F4s~-/%55:%b5@%BD%9e_:@:z:%a3%53/*%b7$//l:l@=%33%E5%B1:@.f@;%5b/%EA%35:j@%Ca,::xu/e:/r):@u'@%e3/%68u$&$;@*--%d4%c2$)::~%A3:M/%5a@@.:%3B,:(:@:::%b0/,@%57!-)@')@/q@@;%78:/@~&:~%5c(*(:@%C1-%3b:?//:?@/v#??:@?://@/
```

The parser crashes on the 10th digit of the number `10653127493172`.

The test input is originally from a ScalaCheck generator and ScalaCheck is not shrinking it properly, hence the crazy URL.

**Comment by theon** [comment]
Hi @dmurvihill, thanks for raising

Ports are currently limited to `Int.MaxValue` in scala-uri (`2147483647`) since that is the data type they are parsed into. I am reluctant to change it to a larger datatype (such as `BigInt`) unless there is a real world transport that requires larger port numbers, especially since TCP only needs a max of 65535.

What are your thoughts? Do you have a use case for larger ports?

Related: https://github.com/lemonlabsuk/scala-uri/issues/21

**Comment by dmurvihill** [comment]
My only use case is to test my code that generates random URLs for use in tests; I totally get it if that's not worth the effort to go from `Int` to `BigInt` over. In that case, maybe it would be enough to list it in the docs as a deviation from the standard?
