### ISSUE TITLE
Does not accept ipv4 address as last 2 segments of ipv6 address

### ISSUE THREAD

**Issue by dmurvihill** [lemonlabsuk/scala-uri#193]
**Describe the bug**
RFC 3986 allows the least-significant two segments of an IPv6 address to be represented in IPv4 address textual format, but the URL parser does not accept this style.

**To Reproduce**
```scala
val url = "s://@[f4E0:F65b:734E:dc04:026b:8629:226.252.129.66]:3298571?"
Url.parse(url)
```

```
[info]     Message: Invalid URL could not be parsed. Invalid input '.', expected HexDigit or ':' (line 1, column 40):
[info]   s://@[f4E0:F65b:734E:dc04:026b:8629:226.252.129.66]:3298571?
```

**Comment by theon** [comment]
Support for this has been added in version 2.3.0. Thanks again for raising this.

Let me know how you get on with it or if there are any other issues.

**Comment by dmurvihill** [comment]
Thanks, great package! I'm bugging my boss to let me publish the generators I used to find all of these.

**Comment by theon** [comment]
Hope you get it published! I'll keep an eye out.
