### ISSUE TITLE
Any chance this could be released for ScalaJS?

### ISSUE THREAD

**Issue by i-am-the-slime** [lemonlabsuk/scala-uri#2]
I am trying to parse and rewrite uris based on the current state in my webapp. This would greatly help!

**Comment by theon** [comment]
I finally got around to this. I have released `0.5.0` which has scala.js support. Let me know of you have any issues. There is an example of it being used here: https://github.com/lemonlabsuk/scala-uri-scalajs-example

Limitations:

 * No [Public Suffixes](https://github.com/lemonlabsuk/scala-uri#public-suffixes) support. The json file used for this is over 700KB and lazy loaded from the filesystem in the jvm version of scala-uri. Maybe in the future this JSON could be optionally embedded in the scala.js build or loaded from a URL. Not sure. 700KB is a bit heavy for JS used in the browser.

* There was a test using the `GB2312` to check we URL encode Chinese characters correctly. This test fails on scala.js with the error `java.nio.charset.UnsupportedCharsetException: GB2312`. Not much we can do about that. This test now only runs agaist the JVM.

**Comment by theon** [comment]
Another limitation is that [matrix parameters](https://github.com/lemonlabsuk/scala-uri/blob/bb2aed9541955dd53c109e96c1d0801af33e2acf/README.md#matrix-parameters) would not compile under scala.js. I have a suspicion that nobody is using matrix parameters, so I have removed from `0.5.0`. If anyone is using them, raise an issue and I will bring support back.
