### ISSUE TITLE
Failed to parse url that starts with long number

### ISSUE THREAD

**Issue by Orhideous** [lemonlabsuk/scala-uri#20]
The heuristics that determine the presence of the IP address in the autority part of URL, is incorrect.
Capturing too many numbers leads to `java.lang.NumberFormatException`

How to reproduce?
```scala
import io.lemonlabs.uri.Url

Url.parse("https://%1.0fexample.com/" format math.pow(2, 31))
```

**Comment by theon** [comment]
Many thanks for this bug report!

I have published a fix in version `1.1.3`. Let me know if you have any further issues.
