### ISSUE TITLE
Add Scala 2.13 support

### ISSUE THREAD

**Issue by theon** [lemonlabsuk/scala-uri#24]

**Comment by ALPSMAC** [comment]
I see this issue is closed now.  Will there be a 2.13 artifact published?

**Comment by theon** [comment]
Ah, my commit message from adding 2.13-M4 
support caused the issue to close.

I'll reopen until a 2.13.0 version is published. I'll take a look tonight and see if all dependencies have upgraded, and if so, we can also upgrade

**Comment by theon** [comment]
The main library scala-uri depends on is parboiled2, which is not yet published for Scala 2.13. Will keep an eye on this: https://github.com/sirthias/parboiled2/issues/205

**Comment by theon** [comment]
Released as version `1.4.8`
