### ISSUE TITLE
Missing maven release v0.5.0 for Scala 2.12

### ISSUE THREAD

**Issue by lanceon** [lemonlabsuk/scala-uri#3]
As it is documented, version 0.5.0 should be used for Scala 2.12, although only 0.4.17 and 0.4.16 are available in Maven repository: https://mvnrepository.com/artifact/io.lemonlabs/scala-uri_2.12

```
Including scala-uri your project

scala-uri 0.5.x is currently built with support for scala 2.12.x, 2.11.x
Release builds are available in maven central. For SBT users just add the following dependency:

"io.lemonlabs" %% "scala-uri" % "0.5.0"
```

Can you please fix this by publishing this version there?
Thanks.

**Comment by theon** [comment]
Gah. Sorry. Forgot to push the button. I need to work on automating this. It should be in maven central within a couple hours.

**Comment by lanceon** [comment]
Available now. Thanks.
