### ISSUE TITLE
support absolute file system paths 

### ISSUE THREAD

**Issue by phpboyscout** [lemonlabsuk/scala-uri#34]
currently AbsoluteUrl does not support "file:///path/to/file" which is a 100% valid URI 

```
import java.net.URI
import io.lemonlabs.uri.AbsoluteUrl
val path = "file:///path/to/file"
val a = new URI(path)
val b = AbsoluteUrl.parse(path)
```

**Comment by theon** [comment]
Thanks for raising this! It highlighted a whole in the tests.

Fixed and released as version `1.4.5`
