### ISSUE TITLE
UrlParser.parseQuery("") crashes

### ISSUE THREAD

**Issue by nafg** [lemonlabsuk/scala-uri#368]
It's unsafe to call `s.head` -- it will crash if `s` is empty.

**Comment by theon** [comment]
Thanks for raising this and sorry for the delay. This is now fixed and will be included in `4.0.0` which I am hoping to release in the next couple of days

**Comment by theon** [comment]
`4.0.0` has now been released. Thanks again for raising this; much appreciated 🙇
