### ISSUE TITLE
Abstract over JSON library or depend on a different one

### ISSUE THREAD

**Issue by pomadchin** [lemonlabsuk/scala-uri#37]
**Description**
The current version of this library depends on a `spray-json` library, that is not popular anymore. The solutions can be: 

1. abstraction over the JSON library
2. depend on smth more popular (for instance [Circe](https://github.com/circe/circe))

It is a great library that I would really like to use, but the `spray-json` dependency makes it not that attractive. 

I would like to hear what are your thoughts about it, thanks!

**Comment by theon** [comment]
I actually thought spray-json had provided scope since it is only used for a small part of scala-uri (specifically the support for public suffixes).

Do you need public suffix support? https://github.com/lemonlabsuk/scala-uri/blob/master/README.md#public-suffixes

I imagine only a small percentage of scala-uri users use public suffixes, so I'd be happy to make spray-json provided so that it doesn't get included in your project. Users that need public suffix support would have to explicitly pull in spray-json in their SBT project.

Would this help?

I'm also happy to abstract over some alternative JSON libraries if needed

**Comment by pomadchin** [comment]
@theon ah, right now it is not `provided`. Btw, `provided` usually always requires manual library adding into the project. Mb it makes sense to mark it as an [optional](https://www.scala-sbt.org/1.x/docs/Scopes.html#Scoping+by+the+configuration+axis) dependency?

https://github.com/lemonlabsuk/scala-uri/blob/master/build.sbt#L22

`"io.spray" %%  "spray-json" % "1.3.4" % Optional`

I will try to check it out in a while and will put here some results (would it work or not). As a short fix it may work :+1: I definitely don't need public suffixes for now. Thanks for such a quick response!

**Comment by theon** [comment]
I didn't know about optional scope. That definitely sounds more appropriate that provided. Thanks!

**Comment by OlegYch** [comment]
using optional dependency is not very friendly as the library fails at runtime in unpredictable way
i'd suggest moving this functionality to a separate module

**Comment by theon** [comment]
> using optional dependency is not very friendly as the library fails at runtime in unpredictable way
> i'd suggest moving this functionality to a separate module

That's a good call, thanks. Currently in the 2.0.0 branch multiple json libraries are supported, so before closing this issue I will plan to:
- Make a separate module per supported json library
- Attempts to use functionality that requires json support in a project with no scala-uri json module included will result in a compile time error

**Comment by theon** [comment]
JSON modules are now published in `2.0.0-M2` and [documentation is here](https://github.com/lemonlabsuk/scala-uri/tree/2.0.0#json-support)

Let me know what you think

**Comment by theon** [comment]
This is a bit daft, but since https://github.com/lemonlabsuk/scala-uri/pull/75 scala-uri no longer needs a JSON library, so the whole issue is a moot point now.

This has been released as `2.0.0-M3`, so closing this issue.
