### ISSUE TITLE
Linking erros on Scala 3 and ScalaJS

### ISSUE THREAD

**Issue by lavrov** [lemonlabsuk/scala-uri#395]
Using classes from `scala-uri` in code results int linking errors.

<details>
<summary>
Compiler output
</summary>
<pre>
Referring to non-existent class io.lemonlabs.uri.Uri
  called from static main.main([java.lang.String)void
  called from core module module initializers
Referring to non-existent class io.lemonlabs.uri.Uri$
  called from main$package$.main()io.lemonlabs.uri.Uri
  called from static main.main([java.lang.String)void
  called from core module module initializers
involving instantiated classes:
  main$package$
Referring to non-existent class io.lemonlabs.uri.Uri
  called from main$package$.main()io.lemonlabs.uri.Uri
  called from static main.main([java.lang.String)void
  called from core module module initializers
involving instantiated classes:
  main$package$
Referring to non-existent class io.lemonlabs.uri.Uri$
  called from main$package$.main()io.lemonlabs.uri.Uri
  called from static main.main([java.lang.String)void
  called from core module module initializers
involving instantiated classes:
  main$package$
Referring to non-existent method io.lemonlabs.uri.Uri$.parse$default$2(java.lang.CharSequence)io.lemonlabs.uri.config.UriConfig
  called from main$package$.main()io.lemonlabs.uri.Uri
  called from static main.main([java.lang.String)void
  called from core module module initializers
involving instantiated classes:
  main$package$
Referring to non-existent method io.lemonlabs.uri.Uri$.parse(java.lang.CharSequence,io.lemonlabs.uri.config.UriConfig)io.lemonlabs.uri.Uri
  called from main$package$.main()io.lemonlabs.uri.Uri
  called from static main.main([java.lang.String)void
  called from core module module initializers
involving instantiated classes:
  main$package$
Referring to non-existent class io.lemonlabs.uri.Uri$
  called from main$package$.main()io.lemonlabs.uri.Uri
  called from static main.main([java.lang.String)void
  called from core module module initializers
involving instantiated classes:
  main$package$
Cannot access module for non-module io.lemonlabs.uri.Uri$
  called from main$package$.main()io.lemonlabs.uri.Uri
  called from static main.main([java.lang.String)void
  called from core module module initializers
involving instantiated classes:
  main$package$
Referring to non-existent class io.lemonlabs.uri.config.UriConfig
  called from main$package$.main()io.lemonlabs.uri.Uri
  called from static main.main([java.lang.String)void
  called from core module module initializers
involving instantiated classes:
  main$package$
Exception in thread "main" org.scalajs.linker.interface.LinkingException: There were linking errors
	at org.scalajs.linker.frontend.BaseLinker.reportErrors$1(BaseLinker.scala:91)
	at org.scalajs.linker.frontend.BaseLinker.$anonfun$analyze$5(BaseLinker.scala:100)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:567)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
</pre>
</details>

**To Reproduce**

```scala
import io.lemonlabs.uri.Uri

@main
def main() =
  Uri.parse("magnet:")
```
Run snippet on Scala 3 and ScalaJS:
```sh
scala-cli --js --dep "io.lemonlabs::scala-uri:4.0.0-M3" -S 3.1.0 main.scala
```
No problem on JVM:
```sh
scala-cli --dep "io.lemonlabs::scala-uri:4.0.0-M3" -S 3.1.0 main.scala
```

**Comment by AlexITC** [comment]
I got something similar with this code `io.lemonlabs.uri.Host.parse(value).value` while using `4.0.0-M3`:

```
[error] Referring to non-existent class io.lemonlabs.uri.Host$
```

**Comment by theon** [comment]
Sorry for the delay; I finally got around to investigating this and it should now be working with version `4.0.0-M4`.

Note: For `scala-cli` there needs to be an extra `:` just before the version number so that it selects the Scala.js platform jar rather than the JVM ([from docs](https://scala-cli.virtuslab.org/docs/reference/dependency/)). A single `:` will give the same error as it will try to use the JVM jar and linking will fail.

```
scala-cli --js --dep "io.lemonlabs::scala-uri::4.0.0-M4" -S 3.1.1 main.scala
Compiling project (Scala 3.1.1, Scala.JS)
Compiled project (Scala 3.1.1, Scala.JS)
```

I was also getting the same error with an SBT project, but that is also now working with `4.0.0-M4`. There is an example here:
https://github.com/lemonlabsuk/scala-uri-scalajs-example

Thanks for raising this and let me know if you have any further issues

**Comment by lavrov** [comment]
@theon Thank you for fixing this! Sorry for incorrect reproduction snippet. I discovered this issue in sbt project intitially. When scala-cli gave me the same error I concluded the cause was the same. I should pay more attention to details.

**Comment by theon** [comment]
No worries! scala-uri was broken, so your conclusion made sense 😄
