### ISSUE TITLE
Scoverage issues in production

### ISSUE THREAD

**Issue by urcadox** [lemonlabsuk/scala-uri#4]
Hello,

I'm having issues with scoverage being used at runtime in a Play app in production mode. It actually tries to write into `/work/scala-uri/jvm/target/scala-2.12/scoverage-data/` (which obviously does not exist so it fails, badly).

Looks like one should not define coverageEnabled in the `build.sbt` file as written here: https://github.com/scoverage/sbt-scoverage/issues/84#issuecomment-273493117

Can you fix this and publish a version without coverage enabled?

**Comment by theon** [comment]
Thanks for reporting this. I didn't know it was possible to publish instrumented classes with scoverage. I was able to reproduce and it should now be fixed in `0.5.0`. I will look to add some integration tests to catch things like this.
