### ISSUE TITLE
file system path doesn't work with relative paths 

### ISSUE THREAD

**Issue by giulio-sefaira** [lemonlabsuk/scala-uri#41]
**Describe the bug**
If you create a Uri("file://pathPart1/file") I would expect the resulting Url to have a path "pathPart1/file" but it turns out as "/pathPart1/file" which makes Uri("file://pathPart1/file") == Uri("file:///pathPart1/file")

**To Reproduce**
```scala
val uri = Uri("file://pathPart1/file")
uri.toString.startsWith("/") must beFalse 
```

**Comment by theon** [comment]
Hi @giulio-sefaira,

Currently, in scala-uri, a URL with a leading double slash `file://pathPart1/file` will have a host of `pathPart1` and a path of `/file` as per [RFC8089](https://tools.ietf.org/html/rfc8089). [This wiki page](https://en.wikipedia.org/wiki/File_URI_scheme#How_many_slashes?) gives a good overview of the RFC.

```scala
scala> val url = Url.parse("file://pathPart1/file")
url: io.lemonlabs.uri.Url = file://pathPart1/file

scala> url.path
res5: io.lemonlabs.uri.UrlPath = /file

scala> url.hostOption
res8: Option[io.lemonlabs.uri.Host] = Some(pathPart1)
```

For representing a local file path, scala-uri supports the leading triple, single and no slash variants defined in RFC8089:

```scala
scala> Url.parse("file:///path/to/file").path
res13: io.lemonlabs.uri.UrlPath = /path/to/file

scala> Url.parse("file:/path/to/file").path
res14: io.lemonlabs.uri.UrlPath = /path/to/file

scala> Url.parse("file:path/to/file").path // See appendix E.2 in the RFC for this format
res15: io.lemonlabs.uri.UrlPath = path/to/file
```

Maybe the last two examples fit your use case? Let me know what you think.

**Comment by theon** [comment]
Also, in case this helps, if you have a path with a leading slash, you wish to drop, you can call `path.toRootless`

```scala
scala> Url.parse("file:///path/to/file").path.toRootless
res21: io.lemonlabs.uri.RootlessPath = path/to/file
```

Let me know what you think.

**Comment by giulio-sefaira** [comment]
Hello Ian, thanks for looking into this. I thought it was a bug, but it's
an overlook of mine.
Thanks again, it's a very good lib.
