### ISSUE TITLE
Parsing `https://\` should fail

### ISSUE THREAD

**Issue by ruurtjan** [lemonlabsuk/scala-uri#429]
**Describe the bug**
Scala-uri currently accepts `https://\` as a valid url, and returns `\` as its host. I didn't read the specs, but I would expect that `\` isn't a valid host name or domain name. In that case, either `parseOption`, or `hostOption` should return a `None`.

**To Reproduce**
```scala
import io.lemonlabs.uri.Url

object BugReport extends App {
  println(Url.parseOption("https://\\").get.hostOption)
  // Prints `Some(\)`
}
```

**Comment by theon** [comment]
Hey @ruurtjan 👋  Thanks for raising this. This should now be fixed in `4.0.2`

**Comment by ruurtjan** [comment]
Hi @theon, thanks for looking into it and publishing a fix 🙏

I haven't read all the relevant RFCs, but isn't it the case that any character besides `a-z`, `0-9`, `.`, `-` and `_` is not allowed in a hostname or domain name?

**Comment by theon** [comment]
> Hi @theon, thanks for looking into it and publishing a fix 🙏
> 
> I haven't read all the relevant RFCs, but isn't it the case that any character besides `a-z`, `0-9`, `.`, `-` and `_` is not allowed in a hostname or domain name?

No worries.

Yes, I think so, but I would like us to support IDN that haven't been resolved to punycode. E.g:

```
scala> val url = io.lemonlabs.uri.Url.parse("https://räksmörgås.josefßon.org")
val url: io.lemonlabs.uri.Url = https://räksmörgås.josefßon.org

scala> url.toStringPunycode // Now we only have (a-z, 0-9, ., - and _)
val res1: String = https://xn--rksmrgs-5wao1o.josefsson.org
```

So as such, we're super permissive of which characters we try to parse as part of a domain name.

I think the rules for which characters we should be allowing in IDNs are quite complex (e.g. any characters that could be used for an IDN homograph attack should not be allowed) and we've not attempted to implement this

**Comment by ruurtjan** [comment]
I see, that makes sense!

Another approach would be to parse IDNs immediately, and represent them as punycode strings in scala-uri. The benefit is that you can be certain a domain name is valid if the parse succeeds. I've had `toStringPunycode` throw exceptions before. I can't trace if it was a because of a different issue than the one I've raised here, unfortunately. The downside is that it would be a breaking change, and you can't distinguish between `Url.parse("https://räksmörgås.josefßon.org")` and Url.parse("https://xn--rksmrgs-5wao1o.josefsson.org"). You'd also need an additional method `toIDN`.

In any case, I'll monitor my error logs to see if there are any additional edge cases that should be covered.

**Comment by theon** [comment]
That's a good point; using the punycode internally would make more sense. The IDN parsing on the way in could be made configurable on/off, so users only dealing with ASCII domain names can choose to not pay any IDN parsing performance hit
