### ISSUE TITLE
Introduce support for IRI

### ISSUE THREAD

**Issue by DamianReeves** [lemonlabsuk/scala-uri#456]
**Description**
I am interested in implementing Linked Data and in particular [JSON-LD](https://json-ld.org/) and a foundational piece of that is [IRI](https://en.wikipedia.org/wiki/Internationalized_Resource_Identifier). Rather than rolling my own, it seems like it makes sense to see if scala-uri could include parsing for this as well.

**Comment by theon** [comment]
Hello! Thanks for raising this.

I've not fully read the [IRI spec](https://datatracker.ietf.org/doc/html/rfc3987), but at a glance, I think many of the things in there are already supported in scala-uri. By default, we already have permissive support unicode, both in domain names (with [punycode](https://www.w3.org/TR/json-ld/#introduction)) and paths/query-strings via percent encoding.

Glancing through the example IRIs in the [json-ld spec here](https://www.w3.org/TR/json-ld/#introduction), they all look like they would parse fine with scala-uri.

Is there a specific aspect of IRIs you've got in mind that is currently missing support in scala-uri?

**Comment by theon** [comment]
Thanks 🙇 If you come across anything whilst working with json-ld, let me know 👍 

I'll take another pass through that IRI spec in the next couple days to double check if anything stands out, and if not will close this issue for now.
