### ISSUE TITLE
Url parsing garbled problem

### ISSUE THREAD

**Issue by erpengwang** [lemonlabsuk/scala-uri#48]
**Describe the bug**
url decode garbled

Example:

```scala
val urlString = "/v1/popplan/?v=6.2.5507.400&did=%e6%44%9b%ca%94%15%9f%0f%3e%aa%16%b7%ca%94%02%e6%8f%a1%9d%5a%b2%9a%78%b7%45%bf%81%93%9b%42%70%c6%36%87%2c%63%5c%fb%f0%7a%67%28%ff%ea%b0%31%7b%27&p=%bf%27%fb%c0%29%7f%14%9a%d0%c2%f3%9e%f9%19%66%fc%6a%8e%45%ee%98%85%0f%9a%52%09%ce%3c%c4%d1%b1%6d%01%5c%d0%fa%5d%74%be%c2%9c%5c%8a%ea%68%f3%9c%c5%df%97%98%09%6f%ed%e6%95%db%76%1b%5d%66%02%4e%11%ae%9c%4d%8d%59%03%24%68%64%ea%dc%3e%5a%5c%0e%8a%1a%eb%71%c9%eb%08%1a%82%fd%93%13%aa%2e%38%d6%64%64%39%07%aa%5b%58%c8%f6%bb%7a%50%e7%97%51%77%a8%81%bc%93%38%df%c8%99%b6%cf%78%91%c5%f9%ae%44%d6%73%bb%f8%ed%05%e3%76%ce%e2%9a%91%63%bf%5c%b1%77%0d%71%45%4f%02%b3%83%db%a9%21%01%04%0b%0a%a8%c7%48%95%b7%82%38%ec%f8%7c%ce%7b%08%f6%78%b6%e4%d3%8a%fa%cc%be%80%06%48%25%d9%45%06%5f%dc%6c%b4%bc%53%d7%8d%d3%a1%4c%a9%7c%75%b2%1f%89%9f%eb%96%2a"
  implicit val c = UriConfig(
    decoder = PercentDecoder(ignoreInvalidPercentEncoding = true)
  )
  val decoderUrl = Url.parse(urlString).toStringRaw.toLowerCase
  println(decoderUrl)
```
result is 
```scala
(qeo��۩!
��h���8��|��x��ӊ�̾�h%�e_�l��s׍ӡl�|u����*  )
```

Can you help me?
    thanks

**Comment by theon** [comment]
Hi, do you know what I supposed to be in that `did` query parameter value?

I tried configuring scala-uri with a few different commonly used charsets ([see here](https://github.com/lemonlabsuk/scala-uri#character-sets)), but still only got garbled text. Maybe `did` is not holding text, but some binary data? It's impossible to say without knowing what is supposed to be in there, which is a question for whoever/whatever created this URL.

**Comment by erpengwang** [comment]
Hello, Do you mean that there is a problem with the URL itself ? but it can be parsed with python's urllib and urllib2. Can't parse the original return, can it be achieved? thanks

**Comment by theon** [comment]
I'm unsure what the exepected output is. Can you show me what the python urllib parses the URL to and I can try to make that happen in scala-uri

**Comment by erpengwang** [comment]
I found the reason, sorry, it is my problem. This url is indeed garbled. The python code is judged by ASCII, so the final result is different. thank you

**Comment by theon** [comment]
Ah great. Glad you found the problem!
