### ISSUE TITLE
Handling generic type of uris

### ISSUE THREAD

**Issue by atais** [lemonlabsuk/scala-uri#6]
Hello

I wanted to use the library, but as for `0.4.17` i experienced some strange issues:

For example for `ftp://` it could work

```
val ftp = "ftp://t49e0444/FilewatcherFS/1990_00_copy/".uri
ftp.path
ftp.protocol
ftp.hostParts

ftp: com.netaporter.uri.Uri = ftp://t49e0444/FilewatcherFS/1990_00_copy/
res0: String = /FilewatcherFS/1990_00_copy/
res1: Option[String] = Some(ftp)
res2: Seq[String] = Vector(t49e0444)
```

But for file?
```
val file = "file:/Downloads/".uri
file.path
file.protocol
file.hostParts

file: com.netaporter.uri.Uri = /file:/Downloads/
res3: String = /file:/Downloads/
res4: Option[String] = None
res5: Seq[String] = Vector()
```

Or worse
```
val file2 = "file://Downloads/".uri
file2.path
file2.protocol
file2.hostParts

file2: com.netaporter.uri.Uri = file://Downloads/
res6: String = /
res7: Option[String] = Some(file)
res8: Seq[String] = Vector(Downloads)
```

it should work with one `/`, but it does not. 
And with `//` it is just strange.

How to approach it?

**Comment by theon** [comment]
Hi!

Thanks for taking the time to message. I haven't looked at any of the File URI specs. I believe scala-uri will support RFC-8089 (the newest file URI spec), but I havent tested that at all. That spec requires three leading slashes when omitting the hostname: see https://en.m.wikipedia.org/wiki/File_URI_scheme#Examples .

I guess your examples with one or two slashes are from an older RFC? I can have a look at the older RFCs and see if it would be easy  to add support for them, but can't guarantee when I will get time for this. If you know which RFC you need supported, let me know.

**Comment by atais** [comment]
Wow, I did not know there is any specification regarding URI. 
I must test it following the latest one then. Thanks!
