### ISSUE TITLE
Use scala-steward?

### ISSUE THREAD

**Issue by takayahilton** [lemonlabsuk/scala-uri#64]
**Description**
>Scala Steward is a robot that helps you keeping library dependencies and sbt plugins up-to-date.

https://github.com/fthomas/scala-steward

**Example**
All you have to do is edit this [repos](https://github.com/scala-steward-org/repos/edit/master/repos.md) and send PR.

**Comment by theon** [comment]
Thanks! PR opened: https://github.com/scala-steward-org/repos/pull/49

**Comment by takayahilton** [comment]
merged
