### ISSUE TITLE
scala-uri_sjs0.6_2.11-0.5.0.pom not published to maven central

### ISSUE THREAD

**Issue by easel** [lemonlabsuk/scala-uri#7]
Pulling down the code and running `sbt +publishLocal` generates the sjs 2.11 jars, so it may be as simple as running `sbt +publish` with the right credentials.

**Comment by theon** [comment]
Thanks for raising this! The 2.11 scala-js build is now up on sonatype [here](https://oss.sonatype.org/content/groups/public/io/lemonlabs/scala-uri_sjs0.6_2.12/) and should make their way to maven central shortly.

I did a quick sanity check with

**Comment by theon** [comment]
(sorry, posted that comment a little early; sonatype servers are being a bit slow, but the jars are uploading...)

**Comment by theon** [comment]
Finally... they have uploaded 😁

**Comment by easel** [comment]
Thanks much! I've been enjoying the library.
